name: OdysseyPlugin
version: 1.0
author: EazyEnder
main: fr.eazyender.odyssey.OdysseyPl
api-version: 1.18
commands:
  item:
    description: Create item, give item
    permission: admin.item
    aliases: i