name: OdysseyPlugin
version: 1.0
author: EazyEnder
main: fr.eazyender.odyssey.OdysseyPl
api-version: 1.18
commands:
  cgive:
    description: Give custom item
    permission: admin.use
    aliases: cg