name: OdysseyPlugin
version: 1.0
author: EazyEnder
main: fr.eazyender.odyssey.OdysseyPl
api-version: 1.18
commands:
  item:
    description: Create item, give item
    permission: admin.item
    aliases: i
  tryspell:
    description: Test spells
    permission: admin.ts
    aliases: ts
  group:
    description: Add a friend to your group
    permission: player.use
    aliases: friend
  accept:
    description: Accept friend request
    permission: player.use
    aliases: yes
  compass:
    description: Change compass resolution
    permission: player.use
    aliases: yes